import { Theme, Preset, BuiltInVisualization } from './types';

export const THEMES: Theme[] = [
  {
    name: 'Neon Nights',
    background: '#0a0a0a',
    primary: '#00f2ea',
    secondary: '#ff00e5',
    highlight: '#ffffff',
  },
  {
    name: 'Sunset Groove',
    background: '#1a0d21',
    primary: '#ff8c00',
    secondary: '#ff007f',
    highlight: '#f0e68c',
  },
  {
    name: 'Forest Mist',
    background: '#122415',
    primary: '#0cff77',
    secondary: '#a0e8af',
    highlight: '#ffffff',
  },
  {
    name: 'Ocean Deep',
    background: '#03132B',
    primary: '#00aeff',
    secondary: '#00f2ea',
    highlight: '#ffffff',
  },
  {
    name: 'Purple Haze',
    background: '#1a0033',
    primary: '#a855f7',
    secondary: '#ec4899',
    highlight: '#fbbf24',
  },
  {
    name: 'Cyberpunk',
    background: '#000000',
    primary: '#ff00ff',
    secondary: '#00ffff',
    highlight: '#ffff00',
  },
  {
    name: 'Midnight Blue',
    background: '#0f172a',
    primary: '#3b82f6',
    secondary: '#8b5cf6',
    highlight: '#f0abfc',
  },
  {
    name: 'Lava Flow',
    background: '#1c0a00',
    primary: '#ff4500',
    secondary: '#ffd700',
    highlight: '#ffffff',
  },
  {
    name: 'Arctic Ice',
    background: '#0a1929',
    primary: '#4dd0e1',
    secondary: '#b3e5fc',
    highlight: '#ffffff',
  },
  {
    name: 'Cherry Blossom',
    background: '#2d1b2e',
    primary: '#ff6b9d',
    secondary: '#ffc3a0',
    highlight: '#ffffff',
  },
  {
    name: 'Toxic Green',
    background: '#0d1f0d',
    primary: '#39ff14',
    secondary: '#00ff00',
    highlight: '#ffffff',
  },
  {
    name: 'Royal Gold',
    background: '#1a1206',
    primary: '#ffd700',
    secondary: '#ff8c00',
    highlight: '#ffffff',
  },
  {
    name: 'Electric Blue',
    background: '#000814',
    primary: '#00d9ff',
    secondary: '#0096ff',
    highlight: '#ffffff',
  },
  {
    name: 'Rose Gold',
    background: '#2b1b1f',
    primary: '#f7cac9',
    secondary: '#dec1c5',
    highlight: '#ffffff',
  },
  {
    name: 'Matrix Code',
    background: '#000000',
    primary: '#00ff41',
    secondary: '#008f11',
    highlight: '#00ff41',
  },
  {
    name: 'Sunset Beach',
    background: '#1a1226',
    primary: '#ff6b6b',
    secondary: '#ffa500',
    highlight: '#ffe66d',
  },
  {
    name: 'Deep Space',
    background: '#0b0c10',
    primary: '#66fcf1',
    secondary: '#45a29e',
    highlight: '#c5c6c7',
  },
  {
    name: 'Candy Pop',
    background: '#1f0d29',
    primary: '#ff71ce',
    secondary: '#01cdfe',
    highlight: '#fffb96',
  },
  {
    name: 'Autumn Leaves',
    background: '#1a0f0a',
    primary: '#ff6347',
    secondary: '#ffa500',
    highlight: '#ffdb58',
  },
  {
    name: 'Galaxy Purple',
    background: '#0d0221',
    primary: '#a460ed',
    secondary: '#e256d2',
    highlight: '#f0c3f1',
  },
  {
    name: 'Mint Fresh',
    background: '#0f1f14',
    primary: '#98ff98',
    secondary: '#00ff7f',
    highlight: '#f0fff0',
  },
  {
    name: 'Blood Moon',
    background: '#1a0000',
    primary: '#dc143c',
    secondary: '#ff4500',
    highlight: '#ffa07a',
  },
  {
    name: 'Sapphire Dreams',
    background: '#001233',
    primary: '#0066cc',
    secondary: '#4169e1',
    highlight: '#87ceeb',
  },
  {
    name: 'Emerald City',
    background: '#0a2f0a',
    primary: '#50c878',
    secondary: '#3cb371',
    highlight: '#98fb98',
  },
  {
    name: 'Hot Pink',
    background: '#2b0a1f',
    primary: '#ff69b4',
    secondary: '#ff1493',
    highlight: '#ffc0cb',
  },
  {
    name: 'Copper Rust',
    background: '#1f1410',
    primary: '#b87333',
    secondary: '#cd7f32',
    highlight: '#daa520',
  },
  {
    name: 'Neon Lime',
    background: '#0f1a0a',
    primary: '#ccff00',
    secondary: '#adff2f',
    highlight: '#ffffff',
  },
  {
    name: 'Twilight Sky',
    background: '#1a1a2e',
    primary: '#16213e',
    secondary: '#0f3460',
    highlight: '#e94560',
  },
  {
    name: 'Coral Reef',
    background: '#1a1515',
    primary: '#ff7f50',
    secondary: '#ff6347',
    highlight: '#ffa07a',
  },
  {
    name: 'Ice & Fire',
    background: '#0a0a0a',
    primary: '#00ffff',
    secondary: '#ff4500',
    highlight: '#ffffff',
  },
];

export const BUILT_IN_VISUALIZATIONS: BuiltInVisualization[] = [
    { name: 'Frequency Bars', type: 'BARS' },
    { name: 'Waveform', type: 'WAVEFORM' },
    { name: 'Circular Spectrum', type: 'CIRCLE' },
    { name: 'Mirror Bars', type: 'MIRROR_BARS' },
    { name: 'Radial Wave', type: 'RADIAL_WAVE' },
    { name: 'Particle Field', type: 'PARTICLE_FIELD' },
    { name: 'Double Helix', type: 'DOUBLE_HELIX' },
    { name: 'Spiral Galaxy', type: 'SPIRAL_GALAXY' },
    { name: 'Sound Pulse', type: 'SOUND_PULSE' },
    { name: 'Oscilloscope', type: 'OSCILLOSCOPE' },
    { name: 'Frequency Rings', type: 'FREQUENCY_RINGS' },
    { name: 'Starfield', type: 'STARFIELD' },
    { name: 'Wave Circles', type: 'WAVE_CIRCLES' },
    { name: 'Fireworks', type: 'FIREWORKS' },
    { name: 'Equalizer', type: 'EQUALIZER' },
    { name: 'Lightning', type: 'LIGHTNING' },
    { name: 'Kaleidoscope', type: 'KALEIDOSCOPE' },
    { name: 'Bubbles', type: 'BUBBLES' },
    { name: 'Ripples', type: 'RIPPLES' },
    { name: 'Spectral Bands', type: 'SPECTRAL_BANDS' },
    { name: 'Vortex', type: 'VORTEX' },
    { name: 'Pyramid', type: 'PYRAMID' },
    { name: 'Flower', type: 'FLOWER' },
    { name: 'Pulse Grid', type: 'PULSE_GRID' },
    { name: 'Diamond', type: 'DIAMOND' },
    { name: 'Waveform Bars', type: 'WAVEFORM_BARS' },
    { name: 'Neon Tunnel', type: 'NEON_TUNNEL' },
    { name: 'Binary Rain', type: 'BINARY_RAIN' },
    { name: 'Polygon Morph', type: 'POLYGON_MORPH' },
    { name: 'Spectrum Waterfall', type: 'SPECTRUM_WATERFALL' },
    { name: 'Double Sided', type: 'DOUBLE_SIDED' },
    { name: 'Crystal Formation', type: 'CRYSTAL_FORMATION' },
    { name: 'Sine Waves', type: 'SINE_WAVES' },
    { name: 'Radar Scan', type: 'RADAR_SCAN' },
    { name: 'Energy Field', type: 'ENERGY_FIELD' },
    { name: 'Hexagon Grid', type: 'HEXAGON_GRID' },
    { name: 'Circuit Board', type: 'CIRCUIT_BOARD' },
    { name: 'Pulse Beam', type: 'PULSE_BEAM' },
];

export const PRESETS: Preset[] = [
  // Original Presets
  {
    name: 'Deep Dive',
    visualizationName: 'Circular Spectrum',
    themeName: 'Ocean Deep',
  },
  {
    name: 'Retro Bars',
    visualizationName: 'Frequency Bars',
    themeName: 'Sunset Groove',
  },
  {
    name: 'Misty Waves',
    visualizationName: 'Waveform',
    themeName: 'Forest Mist',
  },
  {
    name: 'Neon Party',
    visualizationName: 'Frequency Bars',
    themeName: 'Neon Nights',
  },
  {
    name: 'DNA Flow',
    visualizationName: 'Double Helix',
    themeName: 'Neon Nights',
  },
  {
    name: 'Cosmic Journey',
    visualizationName: 'Spiral Galaxy',
    themeName: 'Ocean Deep',
  },
  {
    name: 'Sunset Pulse',
    visualizationName: 'Sound Pulse',
    themeName: 'Sunset Groove',
  },
  {
    name: 'Forest Mirror',
    visualizationName: 'Mirror Bars',
    themeName: 'Forest Mist',
  },
  {
    name: 'Neon Particles',
    visualizationName: 'Particle Field',
    themeName: 'Neon Nights',
  },
  {
    name: 'Ocean Waves',
    visualizationName: 'Radial Wave',
    themeName: 'Ocean Deep',
  },
  {
    name: 'Retro Scope',
    visualizationName: 'Oscilloscope',
    themeName: 'Sunset Groove',
  },
  {
    name: 'Forest Rings',
    visualizationName: 'Frequency Rings',
    themeName: 'Forest Mist',
  },
  
  // New Themed Presets
  {
    name: 'Purple Dreams',
    visualizationName: 'Kaleidoscope',
    themeName: 'Purple Haze',
  },
  {
    name: 'Cyber Matrix',
    visualizationName: 'Kaleidoscope',
    themeName: 'Cyberpunk',
  },
  {
    name: 'Midnight Starfield',
    visualizationName: 'Starfield',
    themeName: 'Midnight Blue',
  },
  {
    name: 'Volcanic Eruption',
    visualizationName: 'Fireworks',
    themeName: 'Lava Flow',
  },
  {
    name: 'Arctic Aurora',
    visualizationName: 'Wave Circles',
    themeName: 'Arctic Ice',
  },
  {
    name: 'Cherry Petals',
    visualizationName: 'Flower',
    themeName: 'Cherry Blossom',
  },
  {
    name: 'Toxic Vortex',
    visualizationName: 'Vortex',
    themeName: 'Toxic Green',
  },
  {
    name: 'Golden Dynasty',
    visualizationName: 'Pyramid',
    themeName: 'Royal Gold',
  },
  {
    name: 'Electric Storm',
    visualizationName: 'Lightning',
    themeName: 'Electric Blue',
  },
  {
    name: 'Rose Diamond',
    visualizationName: 'Diamond',
    themeName: 'Rose Gold',
  },
  {
    name: 'Matrix Rain',
    visualizationName: 'Spectral Bands',
    themeName: 'Toxic Green',
  },
  {
    name: 'Beach Sunset',
    visualizationName: 'Ripples',
    themeName: 'Sunset Beach',
  },
  {
    name: 'Space Odyssey',
    visualizationName: 'Starfield',
    themeName: 'Deep Space',
  },
  {
    name: 'Candy Dreams',
    visualizationName: 'Bubbles',
    themeName: 'Candy Pop',
  },
  {
    name: 'Autumn Vortex',
    visualizationName: 'Vortex',
    themeName: 'Autumn Leaves',
  },
  {
    name: 'Galaxy Spiral',
    visualizationName: 'Spiral Galaxy',
    themeName: 'Galaxy Purple',
  },
  {
    name: 'Mint Particles',
    visualizationName: 'Particle Field',
    themeName: 'Mint Fresh',
  },
  {
    name: 'Blood Eclipse',
    visualizationName: 'Sound Pulse',
    themeName: 'Blood Moon',
  },
  {
    name: 'Sapphire Rings',
    visualizationName: 'Frequency Rings',
    themeName: 'Sapphire Dreams',
  },
  {
    name: 'Emerald Helix',
    visualizationName: 'Double Helix',
    themeName: 'Emerald City',
  },
  {
    name: 'Hot Pink Party',
    visualizationName: 'Equalizer',
    themeName: 'Hot Pink',
  },
  {
    name: 'Copper Pulse Grid',
    visualizationName: 'Pulse Grid',
    themeName: 'Copper Rust',
  },
  {
    name: 'Lime Lightning',
    visualizationName: 'Lightning',
    themeName: 'Neon Lime',
  },
  {
    name: 'Twilight Scope',
    visualizationName: 'Oscilloscope',
    themeName: 'Twilight Sky',
  },
  {
    name: 'Coral Waves',
    visualizationName: 'Waveform Bars',
    themeName: 'Coral Reef',
  },
  {
    name: 'Elemental',
    visualizationName: 'Fireworks',
    themeName: 'Ice & Fire',
  },
  {
    name: 'Neon Highway',
    visualizationName: 'Neon Tunnel',
    themeName: 'Cyberpunk',
  },
  {
    name: 'Digital Rain',
    visualizationName: 'Binary Rain',
    themeName: 'Matrix Code',
  },
  {
    name: 'Morphing Reality',
    visualizationName: 'Polygon Morph',
    themeName: 'Purple Haze',
  },
  {
    name: 'Rainbow Cascade',
    visualizationName: 'Spectrum Waterfall',
    themeName: 'Candy Pop',
  },
  {
    name: 'Dual Dimension',
    visualizationName: 'Double Sided',
    themeName: 'Ice & Fire',
  },
  {
    name: 'Crystal Palace',
    visualizationName: 'Crystal Formation',
    themeName: 'Sapphire Dreams',
  },
  {
    name: 'Ocean Sine',
    visualizationName: 'Sine Waves',
    themeName: 'Ocean Deep',
  },
  {
    name: 'Radar Lock',
    visualizationName: 'Radar Scan',
    themeName: 'Electric Blue',
  },
  {
    name: 'Power Core',
    visualizationName: 'Energy Field',
    themeName: 'Lava Flow',
  },
  {
    name: 'Hive Mind',
    visualizationName: 'Hexagon Grid',
    themeName: 'Toxic Green',
  },
  {
    name: 'Cyber Circuit',
    visualizationName: 'Circuit Board',
    themeName: 'Electric Blue',
  },
  {
    name: 'Beam Show',
    visualizationName: 'Pulse Beam',
    themeName: 'Neon Nights',
  },
];


export const FFT_SIZE = 2048;
